"use client";

import React, { useEffect, useState } from 'react';
import { useAuth } from '@/context/AuthContext';
import Sidebar from '@/components/Sidebar';
import GlassCard from '@/components/GlassCard';
import { CheckSquare, PlusCircle, Clock, Calendar, Check, AlertCircle, FolderGit2, Users } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

export default function TeamLeaderDashboard() {
  const { token } = useAuth();

  // States
  const [tasks, setTasks] = useState<any[]>([]);
  const [interns, setInterns] = useState<any[]>([]);
  const [projects, setProjects] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  // Create Task Form
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [priority, setPriority] = useState('MEDIUM');
  const [assigneeId, setAssigneeId] = useState('');
  const [projectId, setProjectId] = useState('');
  const [dueDate, setDueDate] = useState('');
  const [taskMsg, setTaskMsg] = useState('');

  const [selectedIntern, setSelectedIntern] = useState<any>(null);
  const [internCommits, setInternCommits] = useState<any[]>([]);
  const [internScorecards, setInternScorecards] = useState<any[]>([]);
  const [internHours, setInternHours] = useState<any[]>([]);
  const [generatingScorecard, setGeneratingScorecard] = useState(false);

  useEffect(() => {
    fetchTLData();
  }, []);

  const fetchTLData = async () => {
    setLoading(true);
    try {
      // 1. Tasks
      const tasksRes = await fetch('/api/tasks', {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      if (tasksRes.ok) {
        setTasks(await tasksRes.json());
      }

      // 2. Projects
      const projRes = await fetch('/api/projects', {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      if (projRes.ok) {
        setProjects(await projRes.json());
      }

      // 3. User lists (specifically interns to assign tasks)
      const usersRes = await fetch('/api/users/list', {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      if (usersRes.ok) {
        const uData = await usersRes.json();
        setInterns(uData.filter((u: any) => u.role === 'INTERN'));
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleSelectIntern = async (intern: any) => {
    setSelectedIntern(intern);
    setInternCommits([]);
    setInternScorecards([]);
    setInternHours([]);
    try {
      // Fetch commits
      const comRes = await fetch(`/api/github/commits/${intern.id}`, {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      if (comRes.ok) setInternCommits(await comRes.json());

      // Fetch scorecards
      const scRes = await fetch(`/api/weekly-scorecard/my/${intern.id}`, {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      if (scRes.ok) setInternScorecards(await scRes.json());

      // Fetch working hours
      const whRes = await fetch(`/api/working-hours/plan/${intern.id}`, {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      if (whRes.ok) setInternHours(await whRes.json());
    } catch (err) {
      console.error('Error fetching intern details:', err);
    }
  };

  const handleGenerateScorecard = async (internId: string) => {
    setGeneratingScorecard(true);
    try {
      const res = await fetch(`/api/weekly-scorecard/generate/${internId}`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        }
      });
      if (res.ok) {
        alert('Weekly scorecard successfully generated by Gemini AI!');
        // Refresh scorecards list
        const scRes = await fetch(`/api/weekly-scorecard/my/${internId}`, {
          headers: { 'Authorization': `Bearer ${token}` }
        });
        if (scRes.ok) setInternScorecards(await scRes.json());
      } else {
        alert('Failed to generate scorecard.');
      }
    } catch {
      alert('Error communicating with database.');
    } finally {
      setGeneratingScorecard(false);
    }
  };

  // Create Task Submit
  const handleCreateTask = async (e: React.FormEvent) => {
    e.preventDefault();
    setTaskMsg('Assigning...');

    try {
      const res = await fetch('/api/tasks', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          title,
          description,
          priority,
          assigneeId,
          projectId: projectId || undefined,
          dueDate,
        })
      });

      if (res.ok) {
        setTaskMsg('Task created and assigned successfully!');
        setTitle('');
        setDescription('');
        setDueDate('');
        fetchTLData();
      } else {
        const err = await res.json();
        setTaskMsg(err.message || 'Creation failed.');
      }
    } catch (err) {
      setTaskMsg('Network error.');
    }
  };

  // Review completed task
  const handleReviewTask = async (taskId: string, approval: 'APPROVED' | 'REJECTED') => {
    try {
      const res = await fetch(`/api/tasks/review/${taskId}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({ approval })
      });

      if (res.ok) {
        alert(`Task marked as ${approval === 'APPROVED' ? 'completed' : 'rejected'}.`);
        fetchTLData();
      } else {
        alert('Review submission failed.');
      }
    } catch (err) {
      alert('Error.');
    }
  };

  if (loading) {
    return (
      <div className="flex h-screen items-center justify-center bg-slate-900 text-slate-100">
        <div className="text-center space-y-3">
          <div className="w-10 h-10 border-4 border-blue-500 border-t-transparent rounded-full animate-spin mx-auto"></div>
          <p className="text-xs text-zinc-500 dark:text-zinc-400">Loading Leader board...</p>
        </div>
      </div>
    );
  }

  // Filter tasks into columns
  const getTasksByStatus = (status: string) => tasks.filter(t => t.status === status);

  return (
    <div className="min-h-screen bg-zinc-50 dark:bg-[#09090b] text-zinc-900 dark:text-zinc-100 flex">
      <Sidebar />

      <main className="flex-1 lg:ml-64 p-8 pt-20 lg:pt-8 space-y-6 overflow-y-auto max-h-screen">
        <div>
          <h1 className="text-3xl font-extrabold tracking-tight">Team Lead Workspace</h1>
          <p className="text-sm text-zinc-500 dark:text-zinc-400 mt-1">Manage active development projects, schedule tasks, and approve completed milestones.</p>
        </div>

        {/* Task Dashboard Column Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
          
          {/* Sprints & Kanban Board Columns (occupies 3 cols) */}
          <div className="lg:col-span-3 space-y-6">
            
            {/* Project Header Capsule */}
            <GlassCard className="p-4 flex flex-wrap justify-between items-center bg-slate-900/40">
              <div className="flex items-center space-x-2">
                <span className="w-2.5 h-2.5 bg-green-500 rounded-full animate-pulse"></span>
                <span className="font-semibold text-white">Active Project:</span>
                <span className="text-zinc-600 dark:text-zinc-400">{projects[0]?.name || 'IdeaTech Core Portal Development'}</span>
              </div>
              <div className="text-xs text-blue-400 font-semibold">{tasks.length} Total Sprint Tasks</div>
            </GlassCard>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
              
              {/* Column 1: Pending */}
              <div className="space-y-3">
                <div className="flex justify-between items-center px-1">
                  <h3 className="text-xs font-bold text-zinc-500 uppercase tracking-wider">Pending</h3>
                  <span className="text-[10px] bg-slate-800 text-zinc-500 dark:text-zinc-400 px-1.5 py-0.2 rounded font-bold">{getTasksByStatus('PENDING').length}</span>
                </div>
                <div className="space-y-3 max-h-[500px] overflow-y-auto pr-1">
                  {getTasksByStatus('PENDING').map(t => (
                    <div key={t.id} className="p-3 bg-slate-900/80 border-t-2 border-t-blue-500 rounded-xl space-y-2">
                      <h4 className="text-xs font-bold text-white leading-normal truncate">{t.title}</h4>
                      <p className="text-[10px] text-zinc-500 dark:text-zinc-400 line-clamp-2">{t.description}</p>
                      <div className="flex justify-between text-[9px] text-slate-500">
                        <span>Due: {new Date(t.dueDate).toLocaleDateString()}</span>
                        <span className="font-bold text-blue-400">{t.priority}</span>
                      </div>
                      <div className="text-[9px] text-slate-500 border-t border-white/5 pt-1.5">Assignee: {t.assignee.firstName}</div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Column 2: Working */}
              <div className="space-y-3">
                <div className="flex justify-between items-center px-1">
                  <h3 className="text-xs font-bold text-zinc-500 uppercase tracking-wider">Working</h3>
                  <span className="text-[10px] bg-slate-800 text-zinc-500 dark:text-zinc-400 px-1.5 py-0.2 rounded font-bold">{getTasksByStatus('WORKING').length}</span>
                </div>
                <div className="space-y-3 max-h-[500px] overflow-y-auto pr-1">
                  {getTasksByStatus('WORKING').map(t => (
                    <div key={t.id} className="p-3 bg-slate-900/80 border-t-2 border-t-purple-500 rounded-xl space-y-2">
                      <h4 className="text-xs font-bold text-white leading-normal truncate">{t.title}</h4>
                      <p className="text-[10px] text-zinc-500 dark:text-zinc-400 line-clamp-2">{t.description}</p>
                      <div className="w-full bg-slate-950 h-1 rounded overflow-hidden mt-1">
                        <div className="bg-purple-500 h-full" style={{ width: `${t.progress}%` }}></div>
                      </div>
                      <div className="flex justify-between text-[9px] text-slate-500">
                        <span>Progress: {t.progress}%</span>
                        <span className="font-bold text-purple-400">{t.priority}</span>
                      </div>
                      <div className="text-[9px] text-slate-500 border-t border-white/5 pt-1.5">Assignee: {t.assignee.firstName}</div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Column 3: Completed */}
              <div className="space-y-3">
                <div className="flex justify-between items-center px-1">
                  <h3 className="text-xs font-bold text-zinc-500 uppercase tracking-wider">Needs Review</h3>
                  <span className="text-[10px] bg-slate-800 text-zinc-500 dark:text-zinc-400 px-1.5 py-0.2 rounded font-bold">{getTasksByStatus('COMPLETED').length}</span>
                </div>
                <div className="space-y-3 max-h-[500px] overflow-y-auto pr-1">
                  {getTasksByStatus('COMPLETED').map(t => (
                    <div key={t.id} className="p-3 bg-slate-900/80 border-t-2 border-t-emerald-500 rounded-xl space-y-2">
                      <h4 className="text-xs font-bold text-white leading-normal truncate">{t.title}</h4>
                      <p className="text-[10px] text-zinc-500 dark:text-zinc-400 line-clamp-2">{t.description}</p>
                      <div className="text-[9px] text-slate-500">Assignee: {t.assignee.firstName}</div>
                      
                      <div className="flex space-x-1.5 pt-1 border-t border-white/5">
                        <button
                          onClick={() => handleReviewTask(t.id, 'APPROVED')}
                          className="flex-1 py-1 bg-emerald-600 hover:bg-emerald-700 text-white rounded text-[9px] font-bold"
                        >
                          Approve
                        </button>
                        <button
                          onClick={() => handleReviewTask(t.id, 'REJECTED')}
                          className="flex-1 py-1 bg-red-600 hover:bg-red-700 text-white rounded text-[9px] font-bold"
                        >
                          Reject
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Column 4: Rejected */}
              <div className="space-y-3">
                <div className="flex justify-between items-center px-1">
                  <h3 className="text-xs font-bold text-zinc-500 uppercase tracking-wider">Rejected</h3>
                  <span className="text-[10px] bg-slate-800 text-zinc-500 dark:text-zinc-400 px-1.5 py-0.2 rounded font-bold">{getTasksByStatus('REJECTED').length}</span>
                </div>
                <div className="space-y-3 max-h-[500px] overflow-y-auto pr-1">
                  {getTasksByStatus('REJECTED').map(t => (
                    <div key={t.id} className="p-3 bg-slate-900/80 border-t-2 border-t-red-500 rounded-xl space-y-2">
                      <h4 className="text-xs font-bold text-red-400 leading-normal truncate">{t.title}</h4>
                      <p className="text-[10px] text-zinc-500 dark:text-zinc-400 line-clamp-2">{t.description}</p>
                      <div className="text-[9px] text-slate-500 border-t border-white/5 pt-1.5">Assignee: {t.assignee.firstName}</div>
                    </div>
                  ))}
                </div>
              </div>

            </div>
          </div>

          {/* Task creation & team listing (occupies 1 col) */}
          <div className="space-y-6">
            
            {/* Create Task Card */}
            <GlassCard>
              <h3 className="text-sm font-bold text-zinc-500 dark:text-zinc-400 uppercase tracking-widest mb-3 flex items-center space-x-1.5">
                <PlusCircle size={16} className="text-blue-400" />
                <span>Assign New Task</span>
              </h3>

              {taskMsg && (
                <div className="p-2 mb-3 rounded-xl bg-slate-900 border border-white/5 text-[10px] text-blue-400 text-center">
                  {taskMsg}
                </div>
              )}

              <form onSubmit={handleCreateTask} className="space-y-3">
                <div>
                  <label className="block text-[10px] text-slate-500 mb-0.5">TASK TITLE *</label>
                  <input
                    type="text"
                    required
                    value={title}
                    onChange={(e) => setTitle(e.target.value)}
                    className="w-full bg-slate-900 border border-white/10 rounded-lg px-3 py-1.5 text-xs text-slate-200 focus:outline-none"
                    placeholder="e.g. Implement layout"
                  />
                </div>
                <div>
                  <label className="block text-[10px] text-slate-500 mb-0.5">DESCRIPTION</label>
                  <textarea
                    rows={2}
                    value={description}
                    onChange={(e) => setDescription(e.target.value)}
                    className="w-full bg-slate-900 border border-white/10 rounded-lg px-3 py-1.5 text-xs text-slate-200 focus:outline-none"
                    placeholder="Tasks specifications..."
                  />
                </div>
                <div>
                  <label className="block text-[10px] text-slate-500 mb-0.5">ASSIGNEE INTERN *</label>
                  <select
                    required
                    value={assigneeId}
                    onChange={(e) => setAssigneeId(e.target.value)}
                    className="w-full bg-slate-900 border border-white/10 rounded-lg px-3 py-1.5 text-xs text-zinc-600 dark:text-zinc-400 focus:outline-none"
                  >
                    <option value="">Select Intern...</option>
                    {interns.map(i => <option key={i.id} value={i.id}>{i.firstName} {i.lastName}</option>)}
                  </select>
                </div>
                
                <div className="grid grid-cols-2 gap-2">
                  <div>
                    <label className="block text-[10px] text-slate-500 mb-0.5">PRIORITY</label>
                    <select
                      value={priority}
                      onChange={(e) => setPriority(e.target.value)}
                      className="w-full bg-slate-900 border border-white/10 rounded-lg px-3 py-1.5 text-xs text-zinc-600 dark:text-zinc-400 focus:outline-none"
                    >
                      <option value="LOW">Low</option>
                      <option value="MEDIUM">Medium</option>
                      <option value="HIGH">High</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-[10px] text-slate-500 mb-0.5">PROJECT</label>
                    <select
                      value={projectId}
                      onChange={(e) => setProjectId(e.target.value)}
                      className="w-full bg-slate-900 border border-white/10 rounded-lg px-3 py-1.5 text-xs text-zinc-600 dark:text-zinc-400 focus:outline-none"
                    >
                      <option value="">Choose...</option>
                      {projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}
                    </select>
                  </div>
                </div>

                <div>
                  <label className="block text-[10px] text-slate-500 mb-0.5">DUE DATE *</label>
                  <input
                    type="date"
                    required
                    value={dueDate}
                    onChange={(e) => setDueDate(e.target.value)}
                    className="w-full bg-slate-900 border border-white/10 rounded-lg px-3 py-1.5 text-xs text-zinc-600 dark:text-zinc-400 focus:outline-none"
                  />
                </div>

                <button
                  type="submit"
                  className="w-full py-2.5 rounded-xl bg-theme-gradient text-white text-xs font-semibold hover:opacity-90 shadow-md"
                >
                  Create & Assign Task
                </button>
              </form>
            </GlassCard>

            {/* Team Members List */}
            <GlassCard>
              <h3 className="text-sm font-bold text-zinc-550 dark:text-zinc-400 uppercase tracking-widest mb-3">Project Team Members (Click to Inspect)</h3>
              <div className="space-y-2">
                {interns.map(intern => (
                  <div 
                    key={intern.id} 
                    onClick={() => handleSelectIntern(intern)}
                    className="flex items-center space-x-2 bg-slate-900/40 p-2.5 rounded-xl border border-white/5 cursor-pointer hover:bg-slate-800/40 transition-all hover:scale-[1.02]"
                  >
                    <div className="w-6 h-6 rounded-full bg-blue-500/10 text-blue-400 font-bold flex items-center justify-center text-xs">
                      {intern.firstName.charAt(0)}
                    </div>
                    <div>
                      <h4 className="text-xs font-bold text-white">{intern.firstName} {intern.lastName}</h4>
                      <p className="text-[9px] text-slate-500 uppercase tracking-wider">Software Intern</p>
                    </div>
                  </div>
                ))}
              </div>
            </GlassCard>

          </div>

        </div>
      </main>

      {/* Intern Detail & AI Performance Analysis Modal */}
      <AnimatePresence>
        {selectedIntern && (
          <div className="fixed inset-0 flex items-center justify-center bg-black/60 backdrop-blur-xs z-50 p-4">
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              className="w-full max-w-3xl rounded-3xl border border-zinc-200 dark:border-zinc-800 p-6 bg-zinc-900 shadow-2xl space-y-5 text-zinc-100 max-h-[90vh] flex flex-col overflow-y-auto"
            >
              <div className="flex justify-between items-center border-b border-zinc-250 dark:border-zinc-800 pb-3">
                <div>
                  <h3 className="text-base font-bold text-white">{selectedIntern.firstName} {selectedIntern.lastName}</h3>
                  <p className="text-[10px] text-zinc-500 font-mono">{selectedIntern.email}</p>
                </div>
                <button
                  onClick={() => setSelectedIntern(null)}
                  className="text-zinc-400 hover:text-white font-bold text-xs bg-zinc-800 hover:bg-zinc-750 px-3 py-1.5 rounded-lg border border-white/5"
                >
                  Close
                </button>
              </div>

              {/* Grid Content */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                
                {/* Left Column: WFH Hours & AI Weekly Scorecards */}
                <div className="space-y-4">
                  {/* Shift Analytics (Planned vs Actual) */}
                  <div className="space-y-3 bg-zinc-950/40 border border-zinc-800 p-4 rounded-2xl">
                    <h4 className="text-xs font-bold text-zinc-400 uppercase tracking-widest border-b border-white/5 pb-2">Shift Analytics (Mon - Fri)</h4>
                    <div className="space-y-2.5">
                      {['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'].map((day) => {
                        const plan = internHours.find(h => h.dayOfWeek === day) || { startTime: '09:00', endTime: '17:00' };
                        const [pStartH, pStartM] = plan.startTime.split(':').map(Number);
                        const [pEndH, pEndM] = plan.endTime.split(':').map(Number);
                        const plannedHours = Math.max(0, (pEndH - pStartH) + (pEndM - pStartM) / 60);

                        // Fallback actual (mock 8h if registered shift)
                        const actualHours = 8.0;

                        return (
                          <div key={day} className="space-y-1 text-[10px]">
                            <div className="flex justify-between text-[9px]">
                              <span className="font-semibold text-zinc-400">{day}</span>
                              <span className="text-zinc-500">Planned: {plannedHours.toFixed(1)}h</span>
                            </div>
                            <div className="w-full bg-slate-800 h-1.5 rounded-full overflow-hidden">
                              <div className="bg-blue-500 h-full" style={{ width: `${Math.min(100, (plannedHours / 12) * 100)}%` }} />
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </div>

                  {/* AI Performance Scorecard triggers */}
                  <div className="bg-zinc-950/40 border border-zinc-800 p-4 rounded-2xl space-y-3">
                    <div className="flex justify-between items-center border-b border-white/5 pb-2">
                      <h4 className="text-xs font-bold text-zinc-400 uppercase tracking-widest">AI Weekly Scorecard</h4>
                      <button
                        onClick={() => handleGenerateScorecard(selectedIntern.id)}
                        disabled={generatingScorecard}
                        className="px-3 py-1 bg-blue-600 hover:bg-blue-700 text-white rounded font-bold text-[10px] shadow transition-colors"
                      >
                        {generatingScorecard ? 'Analyzing...' : 'Generate New'}
                      </button>
                    </div>

                    {internScorecards.length === 0 ? (
                      <p className="text-[10px] text-zinc-500 italic">No scorecards generated yet.</p>
                    ) : (
                      <div className="space-y-3.5 max-h-[220px] overflow-y-auto pr-1">
                        {internScorecards.map((sc: any) => (
                          <div key={sc.id} className="p-3 bg-zinc-900 border border-white/5 rounded-xl space-y-2 text-[10.5px]">
                            <div className="flex justify-between items-center">
                              <span className="text-[9.5px] text-zinc-550 font-mono">End: {new Date(sc.weekEnd).toLocaleDateString()}</span>
                              <span className={`px-1.5 py-0.5 rounded text-[9.5px] font-bold ${sc.score >= 80 ? 'bg-emerald-500/10 text-emerald-400' : 'bg-amber-500/10 text-amber-400'}`}>
                                Score: {sc.score}/100
                              </span>
                            </div>
                            <p className="leading-normal"><strong className="text-zinc-400">Feedback:</strong> "{sc.summary}"</p>
                            <p className="text-[10px] text-blue-400 bg-blue-500/5 p-2 rounded-lg leading-normal">💡 <strong className="text-blue-300">Areas of Improvement:</strong> {sc.areasOfImp}</p>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                </div>

                {/* Right Column: GitHub Commits Log */}
                <div className="space-y-3 bg-zinc-950/40 border border-zinc-800 p-4 rounded-2xl flex flex-col max-h-[460px]">
                  <h4 className="text-xs font-bold text-zinc-400 uppercase tracking-widest border-b border-white/5 pb-2">GitHub Activity Log</h4>
                  {internCommits.length === 0 ? (
                    <p className="text-[10px] text-zinc-500 italic text-center py-12">No recent GitHub pushes or commits detected.</p>
                  ) : (
                    <div className="space-y-3 overflow-y-auto flex-grow pr-1">
                      {internCommits.map((commit: any, index: number) => (
                        <div key={commit.id || index} className="p-2.5 bg-zinc-900 border border-white/5 rounded-xl text-[10.5px] space-y-1">
                          <p className="font-semibold text-zinc-200">{commit.message}</p>
                          <div className="flex justify-between items-center text-[9px] text-zinc-500">
                            <span className="font-mono bg-zinc-800 text-zinc-400 px-1 rounded">{commit.sha.substring(0, 7)}</span>
                            <span>{new Date(commit.date).toLocaleDateString()}</span>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
